feature: Allow forcing clean checkout of plugins
buildkite/agent pull request #1636
Opened 2022-05-13 01:15 UTC by toothbrush

2022-05-17 04:03 UTC, toothbrush commented
Jarryd on the Buildkite slack suggested i ask here.  I've tried to create an integration test for this patch, [here it is](https://github.com/toothbrush/agent/compare/paul/force_pull_plugins...force-pull-integration-test).

It's not acceptable as-is though, because i've struggled to write an integration test that tries to do two test step runs (e.g., run a step, modify the plugin, run the step again and ensure the modified plugin was pulled).  My test runs the Bootstrap bit twice, but (apart from the ugliness of my WIP code) it seems there are mocks or something checking that certain things happen exactly _N_ times, that are failing as a result of the two runs (since perhaps they assume one bootstrap test run per test case).  Do folks have thoughts on how to improve that integration test? (apart from just cleaning it up a bit which i would be happy to do)

2022-05-18 23:14 UTC, moskyb requested changes
kia ora @toothbrush!

First off: Thank you so much for the thorough documentation on a) what you've done and b) how you've got there, it's made reviewing this PR a genuine pleasure.

Secondly: This looks really good! i have one minor note about naming, but that's about it in terms of actual substantive changes for this PR. Awesome work.

re: Integration testing: yeah.... i feel your pain. the tool we use to mock external binaries, `bintest`, is really brittle and hugely difficult to debug when it goes wrong. There's a known (to us at least) issue with one of the integration tests (`TestPreExitHooksFireAfterCancel`) fails on macOS boxes for... reasons. I've looked into what's actually going on to fail the test and come back none the wiser, as it works all good in CI.

All this semi-unrelated waffle is to say: Adding integration tests is awesome, but it's also annoying and difficult. If you can't add an integration test within a reasonable amount of time, at that point, it's on us (Buildkite) as the maintainers to make that process easier. If you're banging your head against the wall to add an integration test and you can't get it to work, don't bother for now. We'll fix up the integration testing process.... at some point. Maybe.

2022-05-19 01:38 UTC, moskyb commented on bootstrap/bootstrap.go
> +
yeah, leave it as is for now i reckon. if people are using this and say that it's too slow then we can put some effort into it, but until then i think this is totally fine.

2022-05-19 01:43 UTC, toothbrush commented on bootstrap/config.go
> +	PluginsForcePull bool `env:"BUILDKITE_PLUGINS_FORCE_PULL"`
Yes, i agree that naming the variable as descriptively & accurately as possible is a good idea. 👍  My suggestion is to rename to:

```golang
	PluginsAlwaysCloneFresh bool `env:"BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH"`
```

2022-05-19 03:38 UTC, toothbrush commented on bootstrap/bootstrap.go
> +
Sounds fair 👍

2022-05-19 03:42 UTC, moskyb commented on bootstrap/config.go
> +	PluginsForcePull bool `env:"BUILDKITE_PLUGINS_FORCE_PULL"`
sounds good to me!

2022-05-19 05:19 UTC, toothbrush commented
> kia ora @toothbrush!

ka mihi @moskyb 😊 (hope i'm saying that right)

> First off: Thank you so much for the thorough documentation on a) what you've done and b) how you've got there, it's made reviewing this PR a genuine pleasure.
> 
> Secondly: This looks really good! i have one minor note about naming, but that's about it in terms of actual substantive changes for this PR. Awesome work.

Thank you for the kind words.  And i totally agree on the naming – i've made a change there.

> re: Integration testing: yeah.... i feel your pain. the tool we use to mock external binaries, `bintest`, is really brittle and hugely difficult to debug when it goes wrong. There's a known (to us at least) issue with one of the integration tests (`TestPreExitHooksFireAfterCancel`) fails on macOS boxes for... reasons. I've looked into what's actually going on to fail the test and come back none the wiser, as it works all good in CI.

It turns out that was exactly what tripped me up, so i've cleaned up my existing integration tests and pushed them to this branch as well.  Let me know what you think.

> All this semi-unrelated waffle is to say: Adding integration tests is awesome, but it's also annoying and difficult. If you can't add an integration test within a reasonable amount of time, at that point, it's on us (Buildkite) as the maintainers to make that process easier. If you're banging your head against the wall to add an integration test and you can't get it to work, don't bother for now. We'll fix up the integration testing process.... at some point. Maybe.

Once i got my head around it it wasn't too bad.  I'm still not 100% satisfied with my own integration tests, notably the change i've made by introducing the `modifyTestPlugin` helper function.  It could be deduped a bit with the `createTestPlugin` function, but that wouldn't be trivial, and since this is "only" test-helper code, i thought i'd avoid gold-plating it.  I am happy to either accept feedback to improve it or leave out this new set of integration tests entirely – up to you.

Thanks for the kind words and good feedback. 🙌

2022-05-19 22:31 UTC, moskyb approved these changes
Awesome work! I'll merge this after we release Agent 3.36, the release is getting a bit chunky as is.

2022-05-21 03:13 UTC, toothbrush commented
I'm tempted to say this PR sufficiently addresses the issue originally raised in https://github.com/buildkite/agent/issues/422 that it can be closed, but my approach is more of a dumb workaround than the smarter approach @lox asked for:

> It would be great to fetch the latest version on each job if the plugin isn't a ref or a symbolic ref

What do folks think?  Close up that dangling issue, or leave it as not-yet-completely-solved?  I considered cc'ing all the folks in that thread who had opinions, but i'll avoid spamming folks just yet until i hear further.

2022-05-27 03:07 UTC, toothbrush commented
Out of curiosity @moskyb, when roughly do you expect this to be?  The lack of this feature is making my plugin dev a hassle.

2022-05-30 02:57 UTC, moskyb commented
i'll merge this now :)

it'll likely be released next time we get critical mass for a release, will likely be less than a month, but could be more.

2022-05-30 02:57 UTC, merged