Extend graceful cancellation to all job phases
buildkite/agent pull request #2654
Opened 2024-02-25 22:16 UTC by david-poirier

### Description

We want to be able to gracefully cancel all phases of a job.

### Context

The graceful job cancellation feature introduced [here](https://github.com/buildkite/agent/pull/2250) is great but only applies to the checkout phase of a job.

### Changes

- Use a cancellable context in all phases where processes are being run
- Pass `BUILDKITE_SIGNAL_GRACE_PERIOD_SECONDS` between the agent and executor

### Testing

- [x] Tests have run locally (with `go test ./...`). Buildkite employees may check this if the pipeline has run automatically.
- [x] Code is formatted (with `go fmt ./...`)

2024-02-29 05:10 UTC, moskyb requested changes
hey! i just wanna say this is awesome work. as i mentioned on slack, cancellation is super complicated - much more complicated than the diff here might suggest, to anyone passing by. this looks really good.

i have a couple of suggested changes, but after those are in i'd be happy to merge this - one of the changes should fix your test issue.

2024-02-29 05:10 UTC, moskyb commented on internal/job/executor.go
>  	cancelCtx, cancel := context.WithCancel(ctx)
given that this is now the default context for the executor, i think we should just call it `ctx` - it encourages people to use this one as it seems like the default

2024-02-29 05:10 UTC, moskyb commented on internal/job/executor.go
> +		if err = e.tearDown(cancelCtx); err != nil {
this is the exception to my comment above - `tearDown` still happens after a job is cancelled, and so shouldn't be called with a cancellable context.

i think we'll need to rename the context before the call to `context.WithCancel` to something like `nonCancelContext`, and then pass the non-cancel context into `tearDown`

2024-03-07 06:22 UTC, DrJosh9000 commented on internal/job/executor.go
> +		case <-nonCancelCtx.Done():
I mentioned to @moskyb that the `select` could be simplified away, since `<-nonCancelCtx.Done()` won't ever happen, looks like they did that

2024-03-07 06:22 UTC, DrJosh9000 approved these changes
Makes sense to me! 🥬

2024-03-07 11:06 UTC, moskyb approved these changes

2024-03-07 22:28 UTC, merged